# variables:
# DOCKER_HOST: tcp://localhost:2375

# variables:
#   DOCKER_DRIVE: overlay2

# services:
#   - docker:dind

stages:
  - build

# image:
#   name: docker/compose:latest

before_script:
  - docker buildx

install-buildx:
  stage: install-buildx
  tags:
    - withme-build
  script:
    - LATEST=$(wget -qO- "https://api.github.com/repos/docker/buildx/releases/latest" | jq -r .name)
    - wget https://github.com/docker/buildx/releases/download/$LATEST/buildx-$LATEST.linux-arm64
    - chmod a+x buildx-$LATEST.linux-arm64
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx-$LATEST.linux-arm64 ~/.docker/cli-plugins/docker-buildx

build:
  stage: build
  tags:
    - withme-build
  script: "docker buildx build --platform linux/x86-64 -t gitlab.dyhs.kr/withme ."
