# variables:
# DOCKER_HOST: tcp://localhost:2375

# variables:
#   DOCKER_DRIVE: overlay2

# services:
#   - docker:dind

stages:
  - build

# image:
#   name: docker/compose:latest

before_script:
  - docker buildx

build:
  stage: build
  tags:
    - withme-build
  script: "docker buildx build --platform linux/x86-64 -t gitlab.dyhs.kr/withme ."
