variables:
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build

image:
  name: docker/compose:latest

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  tags:
    - build
  script: "docker-compose build"
